--SELECT COUNT( ORDERID) AS TotaleOrdini FROM ORDERS
--SELECT COUNT(CUSTOMERID) AS TotaleClienti FROM CUSTOMERS
--SELECT COUNT(CUSTOMERID) AS ClientiDiLondra FROM CUSTOMERS WHERE City = 'London'
--SELECT AVG(FREIGHT) AS TotaleSpeseTrasporto FROM ORDERS
--SELECT AVG(FREIGHT) AS TotaleSpeseTrasporto FROM ORDERS WHERE CUSTOMERID ='BOTTM'
--SELECT CUSTOMERID, SUM(FreighT) as TotaleSpeseTrasporto FROM Orders GROUP BY CustomerId
--SELECT city, COUNT(CUSTOMERID)AS ClientiPerCittà FROM CUSTOMERS GROUP BY city
--SELECT ORDERID,SUM(UNITPRICE*QUANTITY)AS TotaleOrderPrice FROM [Order Details] GROUP BY ORDERID
--SELECT SUM(UNITPRICE*QUANTITY)AS TotaleOrder10248 FROM [Order Details] WHERE OrderId = 10248 
--SELECT CATEGORYID, COUNT(PRODUCTID) AS Censimento FROM PRODUCTS GROUP BY CATEGORYID
--SELECT SHIPCOUNTRY, COUNT(ORDERID) AS ORDERiNCOUNTRY FROM ORDERS GROUP BY SHIPCOUNTRY
SELECT SHIPCOUNTRY, AVG(FREIGHT) AS MediaSpeseTrasporto FROM ORDERS GROUP BY SHIPCOUNTRY





-- LA MEDIA ARITMETICA DELLE SPESE DI TRASPORTO DI TUTTI GLIN ORDINI
 